<?xml version="1.0"?>
<package format="2">
  <name>face_recognition_ros1_interfaces</name>
  <version>1.0.0</version>
  <description>ROS1 message and service interfaces for face recognition node</description>
  <maintainer email="user@example.com">User</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>

  <export>
  </export>
</package>
